name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Install Node.js (use correct version)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Change based on your project's Node version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build Next.js app
      - name: Build app
        run: npm run build

      # Step 5: Create build.zip
      - name: Zip the build files
        run: zip -r build.zip .next public package.json next.config.js node_modules

      # Step 6: Transfer build.zip to EC2
      - name: Transfer build.zip to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: 'build.zip'
          target: '~/findtute/'

      # Step 7: SSH into EC2 and unzip/deploy
      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/findtute
            sudo unzip -o build.zip -d .
            rm -f build.zip
            pm2 restart findtute
            pm2 status findtute
            echo "Deployment complete!"
